server:
  port: 8899
spring:
  application:
    name: example-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
halo:
  data:
    isolation:
      enable: true #是否开启数据隔离器
      handler-interceptor-name: dataIsolationHandlerInterceptor #指定数据隔离拦截器名称


mybatis:
  mapper-locations: classpath:mapper/*.xml
